site_name: Wagtail Live
repo_url: https://github.com/wagtail/wagtail-live
edit_uri: blob/main/docs/
theme:
  name: 'material'
  palette:
    primary: 'teal'
    accent: 'indigo'
markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
nav:
  - Home: index.md
  - Getting started:
    - Tutorial: getting_started/tutorial.md
    - Setup Slack Events API receiver: getting_started/setup_slack.md
    - Setup a local web server with ngrok: getting_started/setup_ngrok.md
  - Topics:
    - Input sources and receivers: topics/input_source_and_receivers.md
    - Wagtail Live Interface: topics/wagtail_live_interface.md
    - Publishers: topics/publishers.md
  - Development: development.md
